name: test_action
on: workflow_dispatch
jobs:
  print_output:
    runs-on: ubuntu-latest
    
    steps:
    - name: print hai
      run: echo 'hai' 
  
  print_second_output:
    runs-on: ubuntu-latest
    needs: print_output
    
    steps:
    - name: print Bye
      run: echo 'Bye Bye'
  
